### ISSUE TITLE
This module requires doctrine-orm-module 0.8 so it is not installable with later versions

### ISSUE THREAD

**Issue by berturion** [eddiejaoude/zf2-doctrine2-manager-registry-service#3]
Hello,
I tried to add your module in my current composer.json file but I encountered this error:

    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - eddiejaoude/zf2-doctrine2-manager-registry-service v0.1 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - eddiejaoude/zf2-doctrine2-manager-registry-service 0.4.2 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - eddiejaoude/zf2-doctrine2-manager-registry-service 0.4.1 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - eddiejaoude/zf2-doctrine2-manager-registry-service 0.4 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - eddiejaoude/zf2-doctrine2-manager-registry-service 0.3 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - eddiejaoude/zf2-doctrine2-manager-registry-service 0.2 requires doctrine/doctrine-orm-module 0.8 -> no matching package found.
        - Installation request for eddiejaoude/zf2-doctrine2-manager-registry-service ~0 -> satisfiable by eddiejaoude/zf2-doctrine2-manager-registry-service[0.2, 0.3, 0.4, 0.4.1, 0.4.2, v0.1].

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Is it possible to change requirements if this module is compatible with later version of doctrine-orm-module like v0.9.1 for example ?

**Comment by berturion** [comment]
I forked your project and simply replaced composer.json entry:

    "doctrine/doctrine-orm-module": "0.8"

with:

    "doctrine/doctrine-orm-module": "0.*"

And it works !

Thank you for your module. I don't understand why there is no factory for ManagerRegistry and no factory for DoctrineObjectConstructor in https://github.com/Spea/JMSSerializerModule. Your module solves this and allow me to cache serialized doctrine entities in session for further use.

**Comment by eddiejaoude** [comment]
Ok great work! If you want create a Pull Request against the project & I will accept it. 

*Note: I would not cache to the Session.*

**Comment by berturion** [comment]
Well, it is not a cache, I miswritten this. I store in session a part of an entity that have configuration values for the current logged user and that I need regularly in my app... and you're right, session is not the place to do cache ! Memcached is good (when available) in hosting.
I am pretty new to pull requests, I don't know how to do this but I'll try (googling it) :)

**Comment by eddiejaoude** [comment]
> Well, it is not a cache, I miswritten this. I store in session a part of an entity that have configuration values for the current logged user and that I need regularly in my app... and you're right, session is not the place to do cache ! Memcached is good (when available) in hosting.

Ah ok, no problem :smile: 

> I am pretty new to pull requests, I don't know how to do this but I'll try (googling it) :)

Don't feel you have too, but as you did the work, I wanted you to get the credit. Otherwise, I can make the change. GitHub Pull Request docs https://help.github.com/articles/creating-a-pull-request/

**Comment by berturion** [comment]
Thanks for the link. No problem with credits. I am already proud to share this issue with your project. I think you will be quicker than me to update the project !

**Comment by eddiejaoude** [comment]
Ok, I will make the change now.

**Comment by eddiejaoude** [comment]
Thanks for your support @berturion . 

There is now a new release https://github.com/eddiejaoude/zf2-doctrine2-manager-registry-service/releases/tag/v0.5.0

**Comment by berturion** [comment]
Cool :)
